// <auto-generated />
namespace SVG.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using Microsoft.EntityFrameworkCore.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _202512131500 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202512131500));
        
        string IMigrationMetadata.Id
        {
            get { return "202512131801183_202512131500"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
