// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SVG.Infra.Migrations
{
  [DbContext(typeof(SVG.Infra.Context.SQLServer.SQLServerContext))]
  [Migration("202511112142098_Initial")]
  partial class Initial
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.0");

      modelBuilder.Entity("SVG.Domain.Entities.Operador", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("Matricula")
                      .HasColumnType("varchar(500)");

            b.Property<string>("Nome")
                      .HasColumnType("varchar(500)");

            b.Property<string>("Sessao")
                      .HasColumnType("varchar(500)");

            b.HasKey("ID");

            b.ToTable("Operador");
          });
    }
  }
}
