// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SVG.Infra.Migrations
{
    [DbContext(typeof(SVG.Infra.Context.SQLServer.SQLServerContext))]
    [Migration("202511272112305_202511271810")]
    partial class _202511271810
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
        }
    }
}
