// <auto-generated />
namespace SVG.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _202602111155 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202602111155));
        
        string IMigrationMetadata.Id
        {
            get { return "202602111455436_202602111155"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
