// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SVG.Infra.Context.SQLServer;

#nullable disable

namespace SVG.Infra.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("202601091456310_202601091200")]
    public partial class _202601091200
    {
        // EF Core designer file: contains the model snapshot (BuildTargetModel).
        // Up/Down are implemented in the non-designer migration file.

        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty. If EF Core scaffolded this migration, populate
            // modelBuilder with the model snapshot. Left blank to avoid changing schema.
        }
    }
}
