// <auto-generated />
namespace SVG.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _20260320272120 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20260320272120));
        
        string IMigrationMetadata.Id
        {
            get { return "202603280020216_20260320272120"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
